version: "3.8"
services:
  service:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  db:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: unless-stopped
#  redis:
#    build:
#      context: redis
#      dockerfile: Dockerfile
#    ports:
#      - "6379:6379"
#    restart: unless-stopped
